name: GitHub Actions Demo
on:
  push:
    branches:
      - main
  repository_dispatch:
  
jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          persist-credentials: false
  
  package:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: package 
        uses: splunk/addonfactory-packaging-toolkit-action@v1.0.3
        with:
          source: ./output/TA-Dropbox/
