name: GitHub Actions Demo
on:
  push:
    branches:
      - main
  repository_dispatch:
  
jobs:

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: splunk/addonfactory-packaging-toolkit-action@v1.0.3
        with:
          source: ./output/TA-Dropbox/
