name: GitHub Actions Demo
on:
  push:
    branches:
      - main
  repository_dispatch:
  
jobs:
  
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: package 
        uses: splunk/appinspect-cli-action@v1.0.0
        with:
          app-path: ./output/microsoft-azure-add-on-for-splunk_311.tgz
