name: GitHub Actions Demo
on:
  push:
    branches:
      - main
  repository_dispatch:
  
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package Splunk Application
        uses: splunk/addonfactory-packaging-toolkit-action@v1.1.0
        with:
          source: ./output/TA-Dropbox
  
  appinspect:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: package 
        uses: splunk/appinspect-cli-action@v1.1.0
        with:
          app_path: ./output/microsoft-azure-add-on-for-splunk_311.tgz
